// Generated by gencpp from file T2/postionResult.msg
// DO NOT EDIT!


#ifndef T2_MESSAGE_POSTIONRESULT_H
#define T2_MESSAGE_POSTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace T2
{
template <class ContainerAllocator>
struct postionResult_
{
  typedef postionResult_<ContainerAllocator> Type;

  postionResult_()
    : nowpostion(0)  {
    }
  postionResult_(const ContainerAllocator& _alloc)
    : nowpostion(0)  {
  (void)_alloc;
    }



   typedef uint32_t _nowpostion_type;
  _nowpostion_type nowpostion;





  typedef boost::shared_ptr< ::T2::postionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::T2::postionResult_<ContainerAllocator> const> ConstPtr;

}; // struct postionResult_

typedef ::T2::postionResult_<std::allocator<void> > postionResult;

typedef boost::shared_ptr< ::T2::postionResult > postionResultPtr;
typedef boost::shared_ptr< ::T2::postionResult const> postionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::T2::postionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::T2::postionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace T2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'T2': ['/home/wangzhiyong/catkin_homeword/src/T2/msg', '/home/wangzhiyong/catkin_homeword/devel/share/T2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::T2::postionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::T2::postionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::T2::postionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::T2::postionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::T2::postionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::T2::postionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::T2::postionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0d498a5cbf8eb949b3c1adc4e99e673";
  }

  static const char* value(const ::T2::postionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0d498a5cbf8eb94ULL;
  static const uint64_t static_value2 = 0x9b3c1adc4e99e673ULL;
};

template<class ContainerAllocator>
struct DataType< ::T2::postionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "T2/postionResult";
  }

  static const char* value(const ::T2::postionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::T2::postionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
uint32 nowpostion\n\
";
  }

  static const char* value(const ::T2::postionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::T2::postionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nowpostion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct postionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::T2::postionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::T2::postionResult_<ContainerAllocator>& v)
  {
    s << indent << "nowpostion: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nowpostion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // T2_MESSAGE_POSTIONRESULT_H
