(cl:defpackage T2-msg
  (:use )
  (:export
   "<LASERPOINT>"
   "LASERPOINT"
   "<POSTIONACTION>"
   "POSTIONACTION"
   "<POSTIONACTIONFEEDBACK>"
   "POSTIONACTIONFEEDBACK"
   "<POSTIONACTIONGOAL>"
   "POSTIONACTIONGOAL"
   "<POSTIONACTIONRESULT>"
   "POSTIONACTIONRESULT"
   "<POSTIONFEEDBACK>"
   "POSTIONFEEDBACK"
   "<POSTIONGOAL>"
   "POSTIONGOAL"
   "<POSTIONRESULT>"
   "POSTIONRESULT"
  ))

