; Auto-generated. Do not edit!


(cl:in-package T2-msg)


;//! \htmlinclude postionFeedback.msg.html

(cl:defclass <postionFeedback> (roslisp-msg-protocol:ros-message)
  ((percent
    :reader percent
    :initarg :percent
    :type cl:float
    :initform 0.0))
)

(cl:defclass postionFeedback (<postionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <postionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'postionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name T2-msg:<postionFeedback> is deprecated: use T2-msg:postionFeedback instead.")))

(cl:ensure-generic-function 'percent-val :lambda-list '(m))
(cl:defmethod percent-val ((m <postionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader T2-msg:percent-val is deprecated.  Use T2-msg:percent instead.")
  (percent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <postionFeedback>) ostream)
  "Serializes a message object of type '<postionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <postionFeedback>) istream)
  "Deserializes a message object of type '<postionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<postionFeedback>)))
  "Returns string type for a message object of type '<postionFeedback>"
  "T2/postionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'postionFeedback)))
  "Returns string type for a message object of type 'postionFeedback"
  "T2/postionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<postionFeedback>)))
  "Returns md5sum for a message object of type '<postionFeedback>"
  "d8ec0a0f9e4c365f68112b4b8ef1808d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'postionFeedback)))
  "Returns md5sum for a message object of type 'postionFeedback"
  "d8ec0a0f9e4c365f68112b4b8ef1808d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<postionFeedback>)))
  "Returns full string definition for message of type '<postionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 percent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'postionFeedback)))
  "Returns full string definition for message of type 'postionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 percent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <postionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <postionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'postionFeedback
    (cl:cons ':percent (percent msg))
))
