; Auto-generated. Do not edit!


(cl:in-package T2-msg)


;//! \htmlinclude postionResult.msg.html

(cl:defclass <postionResult> (roslisp-msg-protocol:ros-message)
  ((nowpostion
    :reader nowpostion
    :initarg :nowpostion
    :type cl:integer
    :initform 0))
)

(cl:defclass postionResult (<postionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <postionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'postionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name T2-msg:<postionResult> is deprecated: use T2-msg:postionResult instead.")))

(cl:ensure-generic-function 'nowpostion-val :lambda-list '(m))
(cl:defmethod nowpostion-val ((m <postionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader T2-msg:nowpostion-val is deprecated.  Use T2-msg:nowpostion instead.")
  (nowpostion m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <postionResult>) ostream)
  "Serializes a message object of type '<postionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nowpostion)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nowpostion)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nowpostion)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nowpostion)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <postionResult>) istream)
  "Deserializes a message object of type '<postionResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'nowpostion)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'nowpostion)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'nowpostion)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'nowpostion)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<postionResult>)))
  "Returns string type for a message object of type '<postionResult>"
  "T2/postionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'postionResult)))
  "Returns string type for a message object of type 'postionResult"
  "T2/postionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<postionResult>)))
  "Returns md5sum for a message object of type '<postionResult>"
  "c0d498a5cbf8eb949b3c1adc4e99e673")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'postionResult)))
  "Returns md5sum for a message object of type 'postionResult"
  "c0d498a5cbf8eb949b3c1adc4e99e673")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<postionResult>)))
  "Returns full string definition for message of type '<postionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 nowpostion~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'postionResult)))
  "Returns full string definition for message of type 'postionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 nowpostion~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <postionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <postionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'postionResult
    (cl:cons ':nowpostion (nowpostion msg))
))
