// Auto-generated. Do not edit!

// (in-package T2.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class postionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.nowpostion = null;
    }
    else {
      if (initObj.hasOwnProperty('nowpostion')) {
        this.nowpostion = initObj.nowpostion
      }
      else {
        this.nowpostion = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type postionResult
    // Serialize message field [nowpostion]
    bufferOffset = _serializer.uint32(obj.nowpostion, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type postionResult
    let len;
    let data = new postionResult(null);
    // Deserialize message field [nowpostion]
    data.nowpostion = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'T2/postionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c0d498a5cbf8eb949b3c1adc4e99e673';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint32 nowpostion
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new postionResult(null);
    if (msg.nowpostion !== undefined) {
      resolved.nowpostion = msg.nowpostion;
    }
    else {
      resolved.nowpostion = 0
    }

    return resolved;
    }
};

module.exports = postionResult;
